### ISSUE TITLE
Generated Midi file cannot be opened properly by VLC / QuickTime Player

### ISSUE THREAD

**Issue by xicheng87** [lucien386/MusicalKits_Converter#87]
I tried a few musicxml files and get the midi file, but I cannot open them with VLC / QuickTime Player. Have you tested this locally and ensure that the generated midi is playable, if so by what software?

**Comment by lucien386** [comment]
I use windows media player and it works fine.. Could you tell me what files did you use?

**Comment by lucien386** [comment]
Furthermore, PotPlayer works as well.

**Comment by xicheng87** [comment]
I tried BeetAnGeSample.musicxml and the generated midi does not play on Mac, maybe I am not using the right software to open it?

**Comment by lucien386** [comment]
maybe. It works fine on my windows10
