### ISSUE TITLE
Vexflow option does not give a meaningful file

### ISSUE THREAD

**Issue by xicheng87** [lucien386/MusicalKits_Converter#88]
I tried to select the `vexflow` file option, and then there is a `result.html` file generated, saying `Loading MIDI Instrument: audio will begin when this message disappears.`.

**Comment by lucien386** [comment]
Theoretically, this is the file generated by music21, but I haven't really figured out how `.scl` files work. Maybe I should disable this feather for now?

**Comment by xicheng87** [comment]
Yes, let's disable it for now as this isnt' quite working (and file a bug)

**Comment by lucien386** [comment]
This seems to be an unfinished feature and music21 developer hasn't fully worked on it yet. There are issues still opening for vexflow on music21 page
