### ISSUE TITLE
Make website https

### ISSUE THREAD

**Issue by xicheng87** [lucien386/MusicalKits_Converter#94]
Making a website https is the new norm these days as security matters. I'd suggest you follow instructions here:

https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/configuring-https.html

Not sure if there is additional cost involved, but you may find out.

**Comment by lucien386** [comment]
will do that tmr.

**Comment by lucien386** [comment]
My original environment, https://test-flask.eba-sgnxtm3j.us-east-1.elasticbeanstalk.co, is now secured

**Comment by xicheng87** [comment]
Sounds good, let's extend this to the actual domain

**Comment by lucien386** [comment]
it seems like I have to use Amazon load balancer in order to make musicalkits.me HTTPS.

**Comment by lucien386** [comment]
But if I make the original site https, will the app be secured already?

**Comment by xicheng87** [comment]
No I don't think so. If you just go to the site, you will see that "not secure" is showing up in browser and that is because it is using the HTTP protocol instead of HTTPS.

**Comment by lucien386** [comment]
It's working now. https://converter.musicalkits.me/
