### ISSUE TITLE
The "Choose your format" bar shows up instantly when first loading the page

### ISSUE THREAD

**Issue by xicheng87** [lucien386/MusicalKits_Converter#95]
You can see this if you observe carefully when you refresh the page, it seems that the "Choose your format" bar shows up quickly and then disappears. 

I think this is a bug (though minor), mind looking into it if you have cycles?

**Comment by lucien386** [comment]
That's caused by jquery animation. I solved it by setting the textbox to `display: none` in CSS and change it back in jquery so that users won't see anything about the textbox when the page is loading.
